"""
Critic Agent
------------
Reviews the generated answer for quality, grounding, and citations.
Can send the answer back for revision if it doesn't meet standards.

Checks:
1. Does the answer actually address the question?
2. Are there citations present?
3. Does the answer avoid hallucination (stays grounded in sources)?
4. Is the answer well-structured and clear?
"""

import os
import sys
import json
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))
from src.agents.state import AgentState
from src.agents.llm_provider import get_llm

load_dotenv()


CRITIC_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a quality reviewer for a research paper Q&A system.
You review answers generated by AI and rate their quality.

Evaluate the answer on these criteria:
1. RELEVANCE: Does the answer address the question asked?
2. CITATIONS: Does the answer cite sources properly?
3. GROUNDING: Does the answer stick to information from the provided sources?
4. CLARITY: Is the answer well-structured and easy to follow?

Rate the overall quality from 1-5:
5 = Excellent, well-cited, directly answers the question
4 = Good, minor issues but acceptable
3 = Acceptable but could be improved
2 = Poor, missing citations or off-topic
1 = Unacceptable, needs complete revision

Respond with ONLY a JSON object:
{{
    "score": <1-5>,
    "relevance": "<brief assessment>",
    "citations": "<brief assessment>",
    "grounding": "<brief assessment>",
    "clarity": "<brief assessment>",
    "needs_revision": <true/false>,
    "revision_suggestion": "<what to improve, or 'none' if acceptable>"
}}"""),
    ("human", """QUESTION: {question}

ANSWER TO REVIEW:
{answer}

NUMBER OF SOURCE PAPERS: {num_papers}

Provide your quality assessment as JSON:"""),
])


class CriticAgent:
    """
    Reviews answers for quality and decides whether revision is needed.

    The critic only sends answers back for revision if they score <= 2.
    Scores of 3+ are passed through (good enough). This prevents
    infinite revision loops on borderline answers.
    """

    MAX_REVISIONS = 1  # Only allow 1 revision attempt to prevent loops

    def __init__(self):
        self.llm = get_llm(temperature=0.0)
        self.chain = CRITIC_PROMPT | self.llm | StrOutputParser()

    def review(self, state: AgentState) -> AgentState:
        """
        Review the answer and decide if it passes quality checks.

        This is a LangGraph node — takes state, returns updated state.
        """
        question = state["question"]
        answer = state.get("answer", "")
        num_papers = state.get("num_papers", 0)
        revision_count = state.get("revision_count", 0)
        trace = state.get("agent_trace", [])

        # Skip critique for general/chitchat responses
        if state.get("route") == "general":
            trace.append({
                "agent": "critic",
                "action": "skipped",
                "reason": "General chat doesn't need review",
            })
            return {
                **state,
                "quality_score": 4,
                "critique": "Skipped (general response)",
                "needs_revision": False,
                "agent_trace": trace,
            }

        # Don't review if we've already revised (prevent infinite loops)
        if revision_count >= self.MAX_REVISIONS:
            trace.append({
                "agent": "critic",
                "action": "skipped",
                "reason": f"Max revisions ({self.MAX_REVISIONS}) reached",
            })
            return {
                **state,
                "quality_score": 3,
                "critique": "Max revisions reached, accepting current answer",
                "needs_revision": False,
                "agent_trace": trace,
            }

        try:
            # Run the critic
            response = self.chain.invoke({
                "question": question,
                "answer": answer,
                "num_papers": num_papers,
            })

            # Parse JSON
            clean = response.strip()
            if clean.startswith("```"):
                clean = clean.split("```")[1]
                if clean.startswith("json"):
                    clean = clean[4:]
                clean = clean.strip()

            result = json.loads(clean)

            score = result.get("score", 3)
            needs_revision = result.get("needs_revision", False) and score <= 2

            critique = (
                f"Score: {score}/5 | "
                f"Relevance: {result.get('relevance', 'N/A')} | "
                f"Citations: {result.get('citations', 'N/A')} | "
                f"Grounding: {result.get('grounding', 'N/A')} | "
                f"Clarity: {result.get('clarity', 'N/A')}"
            )

            trace.append({
                "agent": "critic",
                "action": "reviewed",
                "score": score,
                "needs_revision": needs_revision,
                "suggestion": result.get("revision_suggestion", "none"),
            })

            return {
                **state,
                "quality_score": score,
                "critique": critique,
                "needs_revision": needs_revision,
                "revision_count": revision_count + (1 if needs_revision else 0),
                "agent_trace": trace,
            }

        except Exception as e:
            # If critique fails, pass the answer through
            trace.append({
                "agent": "critic",
                "action": "error",
                "error": str(e),
            })
            return {
                **state,
                "quality_score": 3,
                "critique": f"Critique failed: {e}",
                "needs_revision": False,
                "agent_trace": trace,
            }